<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Ellen Cheng" />


<title>TidyTuesday1</title>

<script src="site_libs/jquery-1.12.4/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="site_libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="site_libs/leaflet-1.3.1/leaflet.js"></script>
<link href="site_libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="site_libs/Proj4Leaflet-1.0.1/proj4-compressed.js"></script>
<script src="site_libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="site_libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="site_libs/leaflet-binding-2.0.2/leaflet.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  { color: #cccccc; background-color: #303030; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ffcfaf; } /* Alert */
code span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #dca3a3; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #f0dfaf; } /* ControlFlow */
code span.ch { color: #dca3a3; } /* Char */
code span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
code span.co { color: #7f9f7f; } /* Comment */
code span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
code span.do { color: #7f9f7f; } /* Documentation */
code span.dt { color: #dfdfbf; } /* DataType */
code span.dv { color: #dcdccc; } /* DecVal */
code span.er { color: #c3bf9f; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #c0bed1; } /* Float */
code span.fu { color: #efef8f; } /* Function */
code span.im { } /* Import */
code span.in { color: #7f9f7f; font-weight: bold; } /* Information */
code span.kw { color: #f0dfaf; } /* Keyword */
code span.op { color: #f0efd0; } /* Operator */
code span.ot { color: #efef8f; } /* Other */
code span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
code span.sc { color: #dca3a3; } /* SpecialChar */
code span.ss { color: #cc9393; } /* SpecialString */
code span.st { color: #cc9393; } /* String */
code span.va { } /* Variable */
code span.vs { color: #cc9393; } /* VerbatimString */
code span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' || rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="customstyles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->



<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Data Analysis Exercise Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Analyses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./Coding.html">First Coding Exercise</a>
    </li>
    <li>
      <a href="./Visualization.html">Visualization: Trump Ratings</a>
    </li>
    <li>
      <a href="./TidyTuesday.html">TidyTuesday: Pizza Stores</a>
    </li>
    <li>
      <a href="./Continuous_Outcome_Analysis.html">Continuous Outcome Analysis</a>
    </li>
    <li>
      <a href="./Variable_Selection.html">Variable Selection Analysis</a>
    </li>
    <li>
      <a href="./Tree_Fitting.html">Tree Fitting Analysis</a>
    </li>
    <li>
      <a href="./TidyTuesday2.html">TidyTuesday2: R Packages</a>
    </li>
  </ul>
</li>
<li>
  <a href="./Author.html">About the Author</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/epid8060fall2019/EllenCheng_dataanalysis">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">TidyTuesday1</h1>
<h4 class="author">Ellen Cheng</h4>
<h4 class="date">15 November, 2019</h4>

</div>


<div id="load-libraries" class="section level2">
<h2>Load Libraries</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw">library</span>(magrittr)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw">library</span>(leaflet)</a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="kw">library</span>(shiny)</a></code></pre></div>
<p>I selected the ‘Barstool’ sports dataset to work with in this exercise. This dataset has pizza ratings from three sectors (critic, public, Barstool staff), pricing, location, and geo-location.</p>
</div>
<div id="get-the-data" class="section level2">
<h2>Get the Data</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">barstool &lt;-<span class="st"> </span>readr<span class="op">::</span><span class="kw">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-01/pizza_barstool.csv&quot;</span>)</a></code></pre></div>
<p>I’ll examine the structure of the dataset and pick out a subset of variables relevant for answering interesting questions with visualizations.</p>
<div id="format-examine-the-data" class="section level3">
<h3>Format &amp; examine the data</h3>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">glimpse</span>(barstool)</a></code></pre></div>
<pre><code>## Observations: 463
## Variables: 22
## $ name                                 &lt;chr&gt; &quot;Pugsley&#39;s Pizza&quot;, &quot;William…
## $ address1                             &lt;chr&gt; &quot;590 E 191st St&quot;, &quot;265 Unio…
## $ city                                 &lt;chr&gt; &quot;Bronx&quot;, &quot;Brooklyn&quot;, &quot;New Y…
## $ zip                                  &lt;dbl&gt; 10458, 11211, 10017, 10036,…
## $ country                              &lt;chr&gt; &quot;US&quot;, &quot;US&quot;, &quot;US&quot;, &quot;US&quot;, &quot;US…
## $ latitude                             &lt;dbl&gt; 40.85877, 40.70808, 40.7537…
## $ longitude                            &lt;dbl&gt; -73.88484, -73.95090, -73.9…
## $ price_level                          &lt;dbl&gt; 1, 1, 1, 2, 2, 1, 1, 1, 2, …
## $ provider_rating                      &lt;dbl&gt; 4.5, 3.0, 4.0, 4.0, 3.0, 3.…
## $ provider_review_count                &lt;dbl&gt; 121, 281, 118, 1055, 143, 2…
## $ review_stats_all_average_score       &lt;dbl&gt; 8.011111, 7.774074, 5.66666…
## $ review_stats_all_count               &lt;dbl&gt; 27, 27, 9, 2, 1, 4, 5, 17, …
## $ review_stats_all_total_score         &lt;dbl&gt; 216.3, 209.9, 51.0, 11.2, 7…
## $ review_stats_community_average_score &lt;dbl&gt; 7.992000, 7.742308, 5.76250…
## $ review_stats_community_count         &lt;dbl&gt; 25, 26, 8, 0, 0, 3, 4, 16, …
## $ review_stats_community_total_score   &lt;dbl&gt; 199.8, 201.3, 46.1, 0.0, 0.…
## $ review_stats_critic_average_score    &lt;dbl&gt; 8.8, 0.0, 0.0, 4.3, 0.0, 0.…
## $ review_stats_critic_count            &lt;dbl&gt; 1, 0, 0, 1, 0, 0, 0, 0, 0, …
## $ review_stats_critic_total_score      &lt;dbl&gt; 8.8, 0.0, 0.0, 4.3, 0.0, 0.…
## $ review_stats_dave_average_score      &lt;dbl&gt; 7.7, 8.6, 4.9, 6.9, 7.1, 3.…
## $ review_stats_dave_count              &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, …
## $ review_stats_dave_total_score        &lt;dbl&gt; 7.7, 8.6, 4.9, 6.9, 7.1, 3.…</code></pre>
<p>I don’t understand (from the data or from the dataset definitions) what the provider ratings are, so I’m going to just use the community, critic, and Dave (barstool staff, it seems) scores. The total score is just the average score multiplied by the count, so I’ll drop the total score columns. Some of the names are very long, so I’ll shorten them for ease of use.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">barstool2 &lt;-<span class="st"> </span>barstool <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb5-2" data-line-number="2"><span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(name, city, zip, latitude, longitude, price_level, <span class="dt">comm_avg =</span> review_stats_community_average_score, <span class="dt">comm_count =</span> review_stats_community_count, <span class="dt">crit_avg =</span> review_stats_critic_average_score, <span class="dt">crit_count =</span> review_stats_critic_count, <span class="dt">dave_avg =</span> review_stats_dave_average_score, <span class="dt">dave_count =</span> review_stats_dave_count) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb5-3" data-line-number="3"><span class="st">  </span><span class="kw">mutate_at</span>(<span class="kw">c</span>(<span class="st">&quot;name&quot;</span>, <span class="st">&quot;city&quot;</span>, <span class="st">&quot;zip&quot;</span>), as.factor)</a></code></pre></div>
<p>Let’s check the data to see if there is anything funny to make note of</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw">summary</span>(barstool2)</a></code></pre></div>
<pre><code>##                           name              city          zip     
##  Joe&#39;s Pizza                :  3   New York   :251   10019  : 25  
##  Bonanno&#39;s New York Pizzeria:  2   Brooklyn   : 20   10012  : 22  
##  Justino&#39;s Pizzeria         :  2   Boston     : 13   10014  : 22  
##  Kiss My Slice              :  2   Las Vegas  : 11   10011  : 17  
##  Little Italy Pizza         :  2   Minneapolis:  8   10036  : 16  
##  Lucali                     :  2   Atlanta    :  6   10003  : 14  
##  (Other)                    :450   (Other)    :154   (Other):347  
##     latitude       longitude        price_level      comm_avg     
##  Min.   :25.79   Min.   :-122.41   Min.   :0.00   Min.   : 0.000  
##  1st Qu.:40.72   1st Qu.: -74.09   1st Qu.:1.00   1st Qu.: 6.075  
##  Median :40.75   Median : -73.99   Median :1.00   Median : 7.225  
##  Mean   :40.19   Mean   : -77.44   Mean   :1.46   Mean   : 6.457  
##  3rd Qu.:40.78   3rd Qu.: -73.97   3rd Qu.:2.00   3rd Qu.: 7.873  
##  Max.   :45.00   Max.   : -70.09   Max.   :3.00   Max.   :10.000  
##  NA&#39;s   :2       NA&#39;s   :2                                        
##    comm_count        crit_avg         crit_count        dave_avg     
##  Min.   :  0.00   Min.   : 0.0000   Min.   :0.0000   Min.   : 0.080  
##  1st Qu.:  3.00   1st Qu.: 0.0000   1st Qu.:0.0000   1st Qu.: 6.200  
##  Median :  7.00   Median : 0.0000   Median :0.0000   Median : 7.100  
##  Mean   : 17.87   Mean   : 0.9717   Mean   :0.1425   Mean   : 6.623  
##  3rd Qu.: 18.00   3rd Qu.: 0.0000   3rd Qu.:0.0000   3rd Qu.: 7.800  
##  Max.   :567.00   Max.   :11.0000   Max.   :5.0000   Max.   :10.000  
##                                                                      
##    dave_count
##  Min.   :1   
##  1st Qu.:1   
##  Median :1   
##  Mean   :1   
##  3rd Qu.:1   
##  Max.   :1   
## </code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1"><span class="co"># There are only two records with NA&#39;s in the data--the NA&#39;s are in the latitude &amp; longitude columns</span></a>
<a class="sourceLine" id="cb8-2" data-line-number="2"><span class="co"># Some pizza place names are represented in more than one row of data</span></a>
<a class="sourceLine" id="cb8-3" data-line-number="3"><span class="co"># There is at least one funny zip code: 1748 (has 4 digits instead of 5)</span></a>
<a class="sourceLine" id="cb8-4" data-line-number="4"><span class="co"># There are cases where comm_count and crit_count are 0. The corresponding average scores for these records should be changed to NA, not zero</span></a>
<a class="sourceLine" id="cb8-5" data-line-number="5"></a>
<a class="sourceLine" id="cb8-6" data-line-number="6"><span class="co"># When counts are zero, change the average score to zero (because it means that no one scored the place)</span></a>
<a class="sourceLine" id="cb8-7" data-line-number="7">barstool2<span class="op">$</span>crit_avg[barstool2<span class="op">$</span>crit_count <span class="op">==</span><span class="st"> </span><span class="dv">0</span>] <span class="co"># first check what the average scores are when the counts are zero--are there cases when actual scores are provided, which might indicate that the count is incorrect? The values are all zero. I should change them to NA</span></a></code></pre></div>
<pre><code>##   [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
##  [36] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
##  [71] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [106] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [141] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [176] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [211] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [246] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [281] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [316] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [351] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [386] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1"><span class="kw">length</span>(barstool2<span class="op">$</span>crit_avg[barstool2<span class="op">$</span>crit_count <span class="op">==</span><span class="st"> </span><span class="dv">0</span>]) <span class="co"># Wow, there are actually a lot of cases where critics didn&#39;t score a pizza place--401 out of 463 places didn&#39;t have a critic&#39;s score</span></a></code></pre></div>
<pre><code>## [1] 401</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1">barstool2<span class="op">$</span>crit_avg[barstool2<span class="op">$</span>crit_count <span class="op">==</span><span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb12-2" data-line-number="2"></a>
<a class="sourceLine" id="cb12-3" data-line-number="3">barstool2<span class="op">$</span>comm_avg[barstool2<span class="op">$</span>comm_count <span class="op">==</span><span class="st"> </span><span class="dv">0</span>] <span class="co"># these are also all zero, and should be changed to NA</span></a></code></pre></div>
<pre><code>##  [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [36] 0 0 0 0 0 0</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="kw">length</span>(barstool2<span class="op">$</span>comm_avg[barstool2<span class="op">$</span>comm_count <span class="op">==</span><span class="st"> </span><span class="dv">0</span>]) <span class="co"># there are only 41 pizza places missing community scores</span></a></code></pre></div>
<pre><code>## [1] 41</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">barstool2<span class="op">$</span>comm_avg[barstool2<span class="op">$</span>comm_count <span class="op">==</span><span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb16-2" data-line-number="2"></a>
<a class="sourceLine" id="cb16-3" data-line-number="3"><span class="co"># Check the summary again...</span></a>
<a class="sourceLine" id="cb16-4" data-line-number="4"><span class="kw">summary</span>(barstool2) <span class="co"># there are now 41 NA&#39;s for comm_avg and 401 NA&#39;s for crit_avg--that is correct</span></a></code></pre></div>
<pre><code>##                           name              city          zip     
##  Joe&#39;s Pizza                :  3   New York   :251   10019  : 25  
##  Bonanno&#39;s New York Pizzeria:  2   Brooklyn   : 20   10012  : 22  
##  Justino&#39;s Pizzeria         :  2   Boston     : 13   10014  : 22  
##  Kiss My Slice              :  2   Las Vegas  : 11   10011  : 17  
##  Little Italy Pizza         :  2   Minneapolis:  8   10036  : 16  
##  Lucali                     :  2   Atlanta    :  6   10003  : 14  
##  (Other)                    :450   (Other)    :154   (Other):347  
##     latitude       longitude        price_level      comm_avg     
##  Min.   :25.79   Min.   :-122.41   Min.   :0.00   Min.   : 1.000  
##  1st Qu.:40.72   1st Qu.: -74.09   1st Qu.:1.00   1st Qu.: 6.400  
##  Median :40.75   Median : -73.99   Median :1.00   Median : 7.375  
##  Mean   :40.19   Mean   : -77.44   Mean   :1.46   Mean   : 7.085  
##  3rd Qu.:40.78   3rd Qu.: -73.97   3rd Qu.:2.00   3rd Qu.: 7.900  
##  Max.   :45.00   Max.   : -70.09   Max.   :3.00   Max.   :10.000  
##  NA&#39;s   :2       NA&#39;s   :2                        NA&#39;s   :41      
##    comm_count        crit_avg        crit_count        dave_avg     
##  Min.   :  0.00   Min.   : 4.000   Min.   :0.0000   Min.   : 0.080  
##  1st Qu.:  3.00   1st Qu.: 6.228   1st Qu.:0.0000   1st Qu.: 6.200  
##  Median :  7.00   Median : 7.100   Median :0.0000   Median : 7.100  
##  Mean   : 17.87   Mean   : 7.256   Mean   :0.1425   Mean   : 6.623  
##  3rd Qu.: 18.00   3rd Qu.: 8.100   3rd Qu.:0.0000   3rd Qu.: 7.800  
##  Max.   :567.00   Max.   :11.000   Max.   :5.0000   Max.   :10.000  
##                   NA&#39;s   :401                                       
##    dave_count
##  Min.   :1   
##  1st Qu.:1   
##  Median :1   
##  Mean   :1   
##  3rd Qu.:1   
##  Max.   :1   
## </code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="co"># Since price levels only range from 0 to 3 as integers, I&#39;ll convert this variable to an ordered factor for graphing</span></a>
<a class="sourceLine" id="cb18-2" data-line-number="2">barstool2<span class="op">$</span>price_level &lt;-<span class="st"> </span><span class="kw">factor</span>(barstool2<span class="op">$</span>price_level)</a>
<a class="sourceLine" id="cb18-3" data-line-number="3"></a>
<a class="sourceLine" id="cb18-4" data-line-number="4"><span class="co"># Extract the data records for pizza places represented more than once in the dataset, to see if they are duplicate records</span></a>
<a class="sourceLine" id="cb18-5" data-line-number="5">dup_names &lt;-<span class="st"> </span>barstool2 <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb18-6" data-line-number="6"><span class="st">  </span><span class="kw">group_by</span>(name) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb18-7" data-line-number="7"><span class="st">  </span><span class="kw">filter</span>(<span class="kw">n</span>() <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb18-8" data-line-number="8"><span class="st">  </span><span class="kw">arrange</span>(name)</a>
<a class="sourceLine" id="cb18-9" data-line-number="9">dup_names[, <span class="kw">c</span>(<span class="st">&quot;name&quot;</span>, <span class="st">&quot;zip&quot;</span>, <span class="st">&quot;latitude&quot;</span>, <span class="st">&quot;longitude&quot;</span>)]</a></code></pre></div>
<pre><code>## # A tibble: 21 x 4
## # Groups:   name [10]
##    name                        zip   latitude longitude
##    &lt;fct&gt;                       &lt;fct&gt;    &lt;dbl&gt;     &lt;dbl&gt;
##  1 Bonanno&#39;s New York Pizzeria 89109     36.1    -115. 
##  2 Bonanno&#39;s New York Pizzeria 89109     36.1    -115. 
##  3 Joe&#39;s Pizza                 90401     34.0    -118. 
##  4 Joe&#39;s Pizza                 10014     40.7     -74.0
##  5 Joe&#39;s Pizza                 10011     40.7     -74.0
##  6 Justino&#39;s Pizzeria          10019     40.8     -74.0
##  7 Justino&#39;s Pizzeria          10004     40.7     -74.0
##  8 Kiss My Slice               10022     40.8     -74.0
##  9 Kiss My Slice               10018     40.8     -74.0
## 10 Little Italy Pizza          10036     40.8     -74.0
## # … with 11 more rows</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="co"># So I looked at this subset of data with &#39;View(dup_names)&#39; and it turns out that the pizza place names that are repeated are chains that have multiple stores, so the data really do represent one store per record </span></a></code></pre></div>
<p>Here are some key things I’ve learned so far from examining the Barstool data:</p>
<ul>
<li>Two records are missing latitude and longitude</li>
<li>Some data records have the same pizza place names, but these are validly independent records because they are different stores (different locations) in the same restaurant chain</li>
<li>Only 13% of the pizza places were scored by a critic</li>
<li>All pizza places were scored by Dave</li>
<li>91% of pizza places were scored by the community</li>
</ul>
</div>
<div id="summarize-by-location" class="section level3">
<h3>Summarize by location?</h3>
<p>It might be interesting to examine the scores grouped by location. Let’s first see what sample sizes are working with –are the data pretty evenly distributed among cities, or among zip codes?</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw">table</span>(<span class="kw">table</span>(barstool2<span class="op">$</span>city)) <span class="co"># 68 cities had only one rated pizza place, one city had 251 rated pizza places</span></a></code></pre></div>
<pre><code>## 
##   1   2   3   4   6   8  11  13  20 251 
##  68   9   6   5   6   1   1   1   1   1</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1">barstool2 <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb23-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(city) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb23-3" data-line-number="3"><span class="st">  </span><span class="kw">tally</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb23-4" data-line-number="4"><span class="st">  </span><span class="kw">top_n</span>(<span class="dv">5</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># which cities had the highest number of rated pizza places? New York City</span></a>
<a class="sourceLine" id="cb23-5" data-line-number="5"><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(n))</a></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   city            n
##   &lt;fct&gt;       &lt;int&gt;
## 1 New York      251
## 2 Brooklyn       20
## 3 Boston         13
## 4 Las Vegas      11
## 5 Minneapolis     8</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="kw">table</span>(<span class="kw">table</span>(barstool2<span class="op">$</span>zip)) <span class="co"># 116 zip codes had only one rated pizza place</span></a></code></pre></div>
<pre><code>## 
##   1   2   3   4   5   6   7   8   9  10  11  14  16  17  22  25 
## 116  22   8   5   5   4   2   2   2   1   2   2   1   1   2   1</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1">barstool2 <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb27-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(zip) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb27-3" data-line-number="3"><span class="st">  </span><span class="kw">tally</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb27-4" data-line-number="4"><span class="st">  </span><span class="kw">top_n</span>(<span class="dv">5</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># which zip had the highest number of rated pizza places? zip code 10019 (n = 25 rated places)</span></a>
<a class="sourceLine" id="cb27-5" data-line-number="5"><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(n))</a></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   zip       n
##   &lt;fct&gt; &lt;int&gt;
## 1 10019    25
## 2 10012    22
## 3 10014    22
## 4 10011    17
## 5 10036    16</code></pre>
<p>I originally thought I might be able to do something interesting with pizza place ratings by city or zip code, but it looks like most cities and zip codes only had one rated pizza place. Among cities, New York City had by far the largest number of rated pizza places (N = 251, with the next highest being Brooklyn with N = 20). Ratings were more evenly spread among zip codes (highest was N = 25 for zip code 10019, followed by N = 22 for zip codes 10012 &amp; 10014). But with the zip codes, also, most (N = 116; 66% of zip codes) had just one rated pizza place.</p>
<p><font color="blue">There are too many cities/zip codes, and the data aren’t well spread among the cities/zip codes, so I don’t want to compare data by these location variables.</font></p>
<p>But here are some questions I can visually explore the data to answer…</p>
</div>
<div id="question-how-well-do-daves-scores-correspond-with-community-scores" class="section level3">
<h3>Question: How well do Dave’s scores correspond with community scores?</h3>
<p>We’ll look at this in a few different ways…</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1"><span class="co"># scatterplot</span></a>
<a class="sourceLine" id="cb29-2" data-line-number="2"><span class="kw">ggplot</span>(barstool2, <span class="kw">aes</span>(<span class="dt">x =</span> dave_avg, <span class="dt">y =</span> comm_avg, <span class="dt">size =</span> comm_count, <span class="dt">color =</span> price_level)) <span class="op">+</span></a>
<a class="sourceLine" id="cb29-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb29-4" data-line-number="4"><span class="st">  </span><span class="kw">scale_colour_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Greens&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb29-5" data-line-number="5"><span class="st">  </span><span class="kw">theme_dark</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb29-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb29-7" data-line-number="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Dave&#39;s score&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Average community score&quot;</span>, <span class="dt">subtitle =</span> <span class="st">&quot;Size of dot is scaled to number of community voters </span><span class="ch">\n</span><span class="st">Price level ranges from 0 (cheap) to 3 (expensive) </span><span class="ch">\n</span><span class="st">White line represents perfect correspondence&quot;</span>)</a></code></pre></div>
<p><img src="TidyTuesday_files/figure-html/Q_Dave_vs_comm1-1.png" width="672" /> <font color="blue"> There is a pretty loose correspondence between Dave’s score and the community score for a pizza place. A few things we notice:</p>
<ul>
<li><p>The community tends to give higher scores than Dave does, especially for the pizza places Dave dislikes</p></li>
<li><p>Dave and the community tend to agree more on the better pizza places</p></li>
<li><p>One of the best-scored pizza place by both Dave and the community (and most scored by the community) has a price level of zero. </font></p></li>
</ul>
<p><strong>Let’s find out what that cheap but good pizza place is…</strong></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1"><span class="co"># I&#39;m guessing these filter values from the graph</span></a>
<a class="sourceLine" id="cb30-2" data-line-number="2">dplyr<span class="op">::</span><span class="kw">filter</span>(barstool2, price_level<span class="op">==</span><span class="dv">0</span>, dave_avg <span class="op">&gt;</span><span class="st"> </span><span class="fl">8.25</span>, comm_avg <span class="op">&gt;</span><span class="st"> </span><span class="fl">8.25</span>, comm_count <span class="op">&gt;</span><span class="st"> </span><span class="dv">200</span>) </a></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   name  city  zip   latitude longitude price_level comm_avg comm_count
##   &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt;          &lt;dbl&gt;      &lt;dbl&gt;
## 1 Sauc… New … 10003     40.7     -74.0 0               8.94        248
## # … with 4 more variables: crit_avg &lt;dbl&gt;, crit_count &lt;dbl&gt;,
## #   dave_avg &lt;dbl&gt;, dave_count &lt;dbl&gt;</code></pre>
<p><font color="blue"> Sauce Pizzeria in New York is the best cheap pizza among the places scored. That’s my kind of pizza place.</font></p>
<p><strong>Compare Dave’s and the community’s scores in other ways…</strong></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1"><span class="co"># dotplot</span></a>
<a class="sourceLine" id="cb32-2" data-line-number="2"><span class="kw">ggplot</span>(barstool2) <span class="op">+</span></a>
<a class="sourceLine" id="cb32-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_dotplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> price_level, <span class="dt">y =</span> dave_avg), <span class="dt">binaxis=</span><span class="st">&#39;y&#39;</span>, <span class="dt">stackdir=</span><span class="st">&#39;center&#39;</span>, <span class="dt">dotsize=</span><span class="fl">0.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb32-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="kw">median</span>(barstool2<span class="op">$</span>dave_avg, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb32-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_text</span>(<span class="dt">x =</span> <span class="fl">0.6</span>, <span class="dt">y =</span> <span class="kw">median</span>(barstool2<span class="op">$</span>dave_avg)<span class="op">+</span><span class="fl">0.5</span>, <span class="dt">label =</span> <span class="kw">median</span>(barstool2<span class="op">$</span>dave_avg), <span class="dt">size =</span> <span class="dv">5</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb32-6" data-line-number="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Price level&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Dave&#39;s score&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Dave&quot;</span>, <span class="dt">subtitle =</span> <span class="st">&quot;(Red line is median score across all price levels; Each point represents a pizza place)&quot;</span>)</a></code></pre></div>
<p><img src="TidyTuesday_files/figure-html/Q_Dave_vs_comm-1.png" width="672" /></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1"><span class="kw">ggplot</span>(barstool2) <span class="op">+</span></a>
<a class="sourceLine" id="cb33-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_dotplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> price_level, <span class="dt">y =</span> comm_avg), <span class="dt">binaxis=</span><span class="st">&#39;y&#39;</span>, <span class="dt">stackdir=</span><span class="st">&#39;center&#39;</span>, <span class="dt">dotsize=</span><span class="fl">0.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb33-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="kw">median</span>(barstool2<span class="op">$</span>comm_avg, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb33-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_text</span>(<span class="dt">x =</span> <span class="fl">0.6</span>, <span class="dt">y =</span> <span class="kw">median</span>(barstool2<span class="op">$</span>comm_avg, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)<span class="op">+</span><span class="fl">0.5</span>, <span class="dt">label =</span> <span class="kw">median</span>(barstool2<span class="op">$</span>comm_avg, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dt">size =</span> <span class="dv">5</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb33-5" data-line-number="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Price level&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Average community score&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Community&quot;</span>, <span class="dt">subtitle =</span> <span class="st">&quot;(Red line is median score across all price levels; Each point represents a pizza place)&quot;</span>)</a></code></pre></div>
<p><img src="TidyTuesday_files/figure-html/Q_Dave_vs_comm-2.png" width="672" /> <font color="blue"> Not much new insight here. We do see that the median community score is higher than Dave’s median score. BUT we don’t have community scores for all the pizza places that Dave scored, so it’s a big misleading to compare median values (for different datasets).</font></p>
<p><strong>Is there anything interesting about the pizza places the community did NOT score?</strong></p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1">comm_scored_med &lt;-<span class="st"> </span><span class="kw">median</span>(barstool2<span class="op">$</span>dave_avg[barstool2<span class="op">$</span>comm_count <span class="op">&gt;</span><span class="dv">0</span>], <span class="dt">na.rm =</span> <span class="ot">TRUE</span>) <span class="co"># 422 values</span></a>
<a class="sourceLine" id="cb34-2" data-line-number="2">comm_NOTscored_med &lt;-<span class="st"> </span><span class="kw">median</span>(barstool2<span class="op">$</span>dave_avg[barstool2<span class="op">$</span>comm_count <span class="op">==</span><span class="dv">0</span>], <span class="dt">na.rm =</span> <span class="ot">TRUE</span>) <span class="co"># 41 values</span></a>
<a class="sourceLine" id="cb34-3" data-line-number="3"></a>
<a class="sourceLine" id="cb34-4" data-line-number="4"><span class="kw">ggplot</span>(barstool2) <span class="op">+</span></a>
<a class="sourceLine" id="cb34-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_dotplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> price_level, <span class="dt">y =</span> dave_avg, <span class="dt">color =</span> comm_count <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="dt">fill =</span> comm_count <span class="op">&gt;</span><span class="dv">0</span>), <span class="dt">binaxis=</span><span class="st">&#39;y&#39;</span>, <span class="dt">stackdir=</span><span class="st">&#39;center&#39;</span>, <span class="dt">dotsize=</span><span class="fl">0.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb34-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="kw">c</span>(comm_scored_med, comm_NOTscored_med), <span class="dt">color =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>), <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb34-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_text</span>(<span class="dt">x =</span> <span class="fl">0.6</span>, <span class="dt">y =</span> comm_scored_med<span class="fl">+0.5</span>, <span class="dt">label =</span> comm_scored_med, <span class="dt">size =</span> <span class="dv">5</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb34-8" data-line-number="8"><span class="st">  </span><span class="kw">geom_text</span>(<span class="dt">x =</span> <span class="fl">0.6</span>, <span class="dt">y =</span> comm_NOTscored_med<span class="fl">+0.5</span>, <span class="dt">label =</span> comm_NOTscored_med, <span class="dt">size =</span> <span class="dv">5</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb34-9" data-line-number="9"><span class="st">  </span><span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;black&quot;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb34-10" data-line-number="10"><span class="st">  </span><span class="kw">scale_fill_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;black&quot;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb34-11" data-line-number="11"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Price level&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Dave&#39;s score&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Dave&#39;s score&quot;</span>, <span class="dt">subtitle =</span> <span class="st">&quot;Each black point represents a pizza place also scored by community; red point = not scored </span><span class="ch">\n</span><span class="st">Horizontal lines are Dave&#39;s median scores for pizza places scored (black) or not (red) by community &quot;</span>)</a></code></pre></div>
<p><img src="TidyTuesday_files/figure-html/no_comm-1.png" width="672" /> <font color="blue"> It looks like the pizza places the community did NOT score tended to be the pizza places that weren’t so good (based on Dave’s scores). It’s strange that Dave’s median for the pizza places the community DID score is still the same as Dave’s median overall (7.1, regardless of whether or not the community participated). I wonder if there were just a lot of pizza places that Dave scored that middle value (7.1), which then provides some buffer on the median score. </font></p>
<p>**Let’s check that out…</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1"><span class="kw">sum</span>(barstool2<span class="op">$</span>dave_avg<span class="op">==</span><span class="fl">7.1</span>)</a></code></pre></div>
<pre><code>## [1] 25</code></pre>
<p><font color="blue"> Yes, there were 25 pizza places that Dave scored 7.1. There were only 41 pizza places that the community didn’t score at all–and some of these were scored (by Dave) above 7.1. So it seems plausible that Dave’s median score could still remain 7.1 when omitting the pizza places NOT scored by the community.</font></p>
</div>
<div id="question-is-there-a-relationship-between-the-number-of-community-members-who-scored-a-pizza-place-and-the-average-community-score-for-that-place" class="section level3">
<h3>Question: Is there a relationship between the number of community members who scored a pizza place, and the average community score for that place?</h3>
<p>I want to take a closer look at this relationship because it was a little difficult to see the pattern clearly in the other scatterplot</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1"><span class="kw">ggplot</span>(barstool2, <span class="kw">aes</span>(<span class="dt">x=</span>comm_count, <span class="dt">y=</span>comm_avg)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb37-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb37-3" data-line-number="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Number of participating community members&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Average community score&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb37-4" data-line-number="4"><span class="st">  </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="TidyTuesday_files/figure-html/Q_commcount_vs_commavg-1.png" width="672" /> <font color="blue"> Okay yes, there is a clear (non-linear) positive relationship between the number of people who scored a pizza place and the average score. That makes sense. Maybe people are more reluctant to give a bad score, so they tend to just give scores for the places they like. Or maybe it’s just because more people go to the better pizza places, so there are more people available to provide a score.</font></p>
</div>
<div id="question-where-are-these-pizza-places-click-for-name" class="section level3">
<h3>Question: Where ARE these pizza places? (click for name)</h3>
<p>For a last figure, let’s just get a sense of where these pizza places are. I was going to color points by scores, but I’ve run out of time to figure this out :(</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1"><span class="kw">leaflet</span>(<span class="dt">data =</span> barstool2) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb38-2" data-line-number="2"><span class="st">  </span><span class="kw">addTiles</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb38-3" data-line-number="3"><span class="st">  </span><span class="kw">setView</span>(<span class="dt">lng=</span><span class="kw">median</span>(barstool2<span class="op">$</span>longitude, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dt">lat=</span><span class="kw">median</span>(barstool2<span class="op">$</span>latitude, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dt">zoom=</span><span class="dv">10</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb38-4" data-line-number="4"><span class="st">  </span><span class="kw">addMarkers</span>(<span class="dt">lng =</span> <span class="op">~</span>longitude,</a>
<a class="sourceLine" id="cb38-5" data-line-number="5">             <span class="dt">lat =</span> <span class="op">~</span>latitude,</a>
<a class="sourceLine" id="cb38-6" data-line-number="6">             <span class="dt">popup =</span> <span class="op">~</span>name)</a></code></pre></div>
<div id="htmlwidget-ab5ea5f97fe33364cd20" style="width:672px;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-ab5ea5f97fe33364cd20">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addTiles","args":["//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",null,null,{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"attribution":"&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap<\/a> contributors, <a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA<\/a>"}]},{"method":"addMarkers","args":[[40.8587693,40.7080823,40.7536996,40.7569012,40.739047,null,40.7971889,40.7983829,40.8008324,40.7593741,39.6319501,39.6501191,39.634409,40.7029363,40.7971469,40.838259,40.9187903,44.9703571,44.9819829,44.8633027,44.9007915,44.9885135,44.9813871,45.0010473,44.9438376,44.9817509,44.9880028,40.7832845,40.7750717,40.7290373,40.7816474,40.7564841,40.7559546,40.7534553,40.7650144,40.7157456,40.714805,40.767267,40.7695645,40.7694782,40.7421252,40.7691562,40.7692221,40.7604259,37.3627256,40.736006,40.7153411,40.726083,40.7580741,41.5737628,41.7197804,41.895939,41.8959836,41.9026134,41.9038129,41.9089261,41.9219194,41.9322675,39.774472,39.7716299,39.76629,41.6667105,41.6796112,38.2565366,38.2557701,38.2276706,38.2042473,42.2719869,42.2779976,42.2743004,42.274698,42.3057179,40.0755657,39.9945638,40.0051012,40.0001458,39.9951727,39.9821407,38.049415,38.0419078,38.0190885,41.0992203,41.0984394,41.084449,41.100117,41.0553955,38.3462309,35.6738093,44.9557263,37.229311,42.8359733,34.0697338,33.8553969,33.8457987,33.8455184,33.956041,33.8091393,33.7846405,33.756896,35.21582,33.4786227,35.485709,39.9390309,39.956304,40.6489809,41.0776986,40.8249129,40.8315592,40.8937863,40.6255479,40.8366184,40.6302068,40.8291884,40.8340373,40.5887642,40.5867953,40.7379143,40.7132,40.7462614,40.7501463,40.7369733,40.7442476,40.7507591,40.7103852,40.7080776,40.7392955,40.7095045,40.7415865,40.63597,40.7048308,40.7033479,40.7040298,40.7042482,40.705371,40.7036197,40.705987,40.7100713,40.7049944,40.7068657,40.712115,40.7092384,40.7151451,40.7074723,40.7256037,40.71961,40.7081961,40.6818032,40.7312196,40.721287,40.734617,40.7237259,40.739633,40.7290939,40.7200998,40.7440765,40.7382727,40.7407714,40.7293862,40.7416944,40.7410115,40.7322097,40.7409959,40.7249388,40.7316187,40.7424509,40.7273153,40.7300735,40.7315345,40.7327781,27.972532,27.9488577,30.3159643,29.3942955,29.424703,29.4895746,28.0773373,29.2315464,30.3010239,25.8877393,25.7951979,25.7917344,26.7128713,26.7009344,40.5788542,40.5947441,40.6249664,40.6728736,32.7116571,32.7496568,32.797433,33.884818,34.0132137,34.0326451,36.09551,36.102576,36.1073485,36.1099462,36.1125269,36.1271069,36.1271069,36.1307814,36.1612877,36.1692503,36.1718292,37.8006205,43.0794291,43.1360475,43.0699236,43.0757068,43.0913224,43.0739705,43.1008889,40.7645266,40.7619108,40.7623377,40.8778717,40.8920639,40.7225396,40.7079094,40.6627285,40.7323691,40.7089715,40.7133121,40.6806956,40.6860591,40.7050886,40.8709751,40.7149868,40.7132095,40.7150459,40.7115836,40.7156098,40.70261,40.7027359,40.7031257,40.7179382,40.7142926,40.7283642,40.7155652,40.719207,40.7294956,40.719503,40.72084,40.7207424,40.7222599,40.721395,40.7176916,40.7216286,40.7257098,40.7183603,40.7190658,40.7266819,40.7188558,40.719646,40.7236857,40.7236056,40.7206081,40.7206548,40.7271342,40.7210784,40.7216368,40.7215205,40.7221166,40.7225943,40.7230533,null,40.7253326,40.7249939,40.7234824,40.7278516,40.7294404,40.7282177,40.728906,40.730205,40.7260551,41.6573714,41.6528616,41.6519358,41.2847682,41.2853859,41.2683804,41.2721365,41.2729464,41.267011,41.7668396,42.107555,42.4720842,42.4195497,41.4571614,41.3892499,41.3907962,42.37266,41.4524,42.364888,42.3637083,42.3645242,42.3654462,42.3670789,42.3592396,42.3650917,42.3595409,42.1985494,42.360973,42.3497463,42.3473912,42.1521674,42.3459093,41.8693793,42.0660348,42.4709405,42.1149423,42.3215125,42.2760134,41.3420782,42.229138,41.4733358,41.3138627,41.3029994,41.3031003,41.3061295,41.0893349,41.0507692,40.9176619,40.8553028,40.7827162,40.7989045,40.8004768,40.7771534,40.7762259,40.775677,40.7709244,40.771291,40.7714577,40.7987416,40.7996265,40.7770858,40.7952921,40.764447,40.7862402,40.7668083,40.7618037,40.7664835,40.7586551,40.7838392,40.7584227,40.7637673,40.7587907,40.7256063,40.7800257,40.7764537,40.775197,40.7292588,40.7303785,40.7261754,40.7273906,40.7281815,40.7288479,40.7294111,40.7305876,40.771542,40.767519,40.7662387,40.7652916,40.7660301,40.763707,40.7657404,40.7655642,40.7655642,40.7656166,40.7638919,40.7634874,40.7656728,40.7626772,40.7644023,40.7603494,40.7627178,40.7649042,40.759987,40.7614264,40.7635749,40.7601189,40.7596624,40.7629267,40.7592788,40.7574739,40.7594681,40.7599841,40.7582117,40.7599841,40.7554122,40.7312068,40.7304367,40.7342727,40.7360768,40.746892,40.7473469,40.7507787,40.748746,40.7429242,40.7438893,40.7510941,40.739882,40.7392653,40.741945,40.7459915,40.7471546,40.7367059,40.7360738,40.7422264,40.7359857,40.7603402,40.7615215,40.7557265,40.7593755,40.755125,40.7566759,40.7565439,40.7595458,40.7570286,40.761057,40.7454027,40.743953,40.750205,40.7290573,40.757071,40.7303784,40.7338794,40.758842,40.7606993,40.7571427,40.7603114,40.7540761,40.7550182,40.7558161,40.7515735,40.7504432,40.7570209,40.760405,40.7570116,40.7535178,40.7548319,40.7510051,40.7488024,40.7527277,40.7496668,40.7451535,40.7450574,40.7462466,40.7524427,40.7498097,40.7496468,40.7297781,40.7540255,40.7443961,40.7348297,40.7399505,40.7385388,40.7409664,40.7473317,40.7450509,40.7450574,40.7398901,40.7421817],[-73.8848374,-73.9509034,-73.9741132,-73.980518,-73.988895,null,-73.9695729,-73.969439,-73.9675901,-73.9861745,-79.9542123,-79.9648861,-79.971237,-73.9874841,-73.934857,-73.8286389,-73.8937123,-93.1062382,-93.2729943,-93.3540843,-93.2477362,-93.25699,-93.2373204,-93.266725,-93.1040853,-93.2735502,-93.2300315,-74.2255033,-73.980868,-74.0015817,-74.1379771,-73.9814704,-73.9800255,-73.996024,-73.9608725,-74.0053843,-74.006577,-73.9841435,-73.9886224,-73.9888845,-73.9836267,-73.9628311,-73.9628197,-73.9616128,-81.0944838,-73.9825421,-73.991428,-73.989775,-73.9847908,-87.4037838,-87.7424228,-87.6256378,-87.6230343,-87.6288955,-87.6291833,-87.8178411,-87.6642989,-87.8062738,-86.1495484,-86.153288,-86.158305,-91.5591346,-91.5906823,-85.7530056,-85.7522846,-85.7354161,-85.7716305,-83.7421382,-83.7417239,-83.7349799,-83.734342,-83.247297,-82.9982614,-83.0141966,-83.0083149,-83.00761,-83.0094102,-82.9984713,-84.4999733,-84.5038044,-84.5218707,-80.7669492,-80.7660943,-80.732878,-80.650357,-80.6038747,-81.6203919,-88.7794935,-93.2781621,-80.4149952,-78.8072699,-84.2945836,-84.3813317,-84.3744938,-84.3689686,-83.9876325,-84.4126296,-84.4056188,-84.3900344,-80.821622,-81.9734034,-97.541423,-75.1592238,-75.241707,-74.2166257,-74.1387265,-74.1531269,-74.1375757,-74.1100941,-74.1437917,-74.1139253,-74.1402479,-74.1001832,-74.0902719,-74.0951739,-74.0914961,-74.0342961,-74.0355525,-74.030223,-74.0296929,-74.0307767,-74.0291561,-74.0271827,-74.0164692,-74.0136934,-74.0087429,-74.0120408,-74.0075955,-74.1312791,-74.0123163,-74.0108472,-74.01048,-74.0101127,-74.0100717,-74.0099715,-74.010097,-74.0103149,-74.0096537,-74.0097069,-74.0097029,-74.0088627,-74.0079738,-74.0068304,-74.0079092,-74.0070307,-74.0047955,-74.0003087,-74.0065106,-74.0049711,-74.0063544,-74.0044625,-74.006657,-74.005017,-74.0035903,-74.0065507,-74.0053786,-74.0058204,-74.0037767,-74.0056597,-74.0048657,-74.003375,-74.0046301,-74.0024003,-74.0034468,-74.0059581,-74.0024806,-74.0027807,-74.0029626,-74.0029512,-82.8282307,-82.4591727,-97.7184605,-98.4041595,-98.4899903,-98.4588608,-80.7047651,-81.0107463,-81.3939898,-80.1639536,-80.1439705,-80.1390831,-80.0502288,-80.0403344,-73.9838179,-73.9813041,-73.9615259,-73.9768734,-117.1594319,-117.1634597,-117.2523779,-118.411124,-118.4962533,-118.4755043,-115.1760672,-115.1702533,-115.1765836,-115.1753911,-115.175947,-115.1648303,-115.1648303,-115.1988255,-115.1456299,-115.1400711,-115.1423178,-122.4090769,-73.8005422,-73.7701491,-73.7946879,-73.7903663,-73.7710902,-73.7679799,-73.7424231,-73.9996076,-74.0001507,-73.9967579,-72.5227702,-72.425907,-73.5777702,-73.6900874,-73.8404131,-73.6874204,-73.8305343,-73.8754214,-73.9674607,-73.9742104,-73.9335742,-73.4264444,-73.9441688,-73.9491414,-73.9447162,-73.9578707,-73.9535064,-73.9932413,-73.9934479,-73.9936086,-73.9637027,-73.9817288,-73.957175,-73.9934694,-73.9845869,-73.9585644,-73.985142,-73.98434,-73.9866989,-73.9829462,-73.9874389,-73.9984062,-73.9886492,-73.9779639,-73.9979471,-73.9969894,-73.9772637,-73.9979012,-73.9969371,-73.9877463,-73.9884144,-73.9965332,-73.9966534,-73.9802714,-73.9967554,-73.9957205,-73.9970345,-73.9963862,-73.9952614,-73.9945497,null,-73.9898267,-73.9927133,-73.9964503,-73.9853674,-73.9812861,-73.9850845,-73.9840414,-73.9807302,-73.9923001,-70.1406268,-70.2840462,-70.2854937,-70.094344,-70.0982049,-70.0858313,-70.0909947,-70.0917998,-70.0999493,-70.5062036,-70.762957,-70.925399,-70.986745,-70.5572867,-70.5120708,-70.5145215,-71.0352918,-70.5988606,-71.0531419,-71.0542803,-71.0553969,-71.057066,-71.0581116,-71.0589677,-71.0615271,-71.0634498,-71.021315,-71.068077,-71.0810917,-71.0820284,-71.0306641,-71.0988281,-70.9320635,-71.0165789,-71.1502244,-71.1011701,-71.1756718,-71.1672475,-70.74509,-71.5200453,-71.9600034,-72.9129505,-72.9169202,-72.9200566,-72.9303245,-73.5184796,-73.527249,-73.8393793,-73.8875914,-73.9478073,-73.9634659,-73.9653026,-73.952629,-73.9532948,-73.9536392,-73.951134,-73.95318,-73.9529963,-73.9673646,-73.9686711,-73.9571289,-73.9707437,-73.958677,-73.9725922,-73.9625052,-73.9601575,-73.9633564,-73.9630182,-73.9775697,-73.9626049,-73.967344,-73.9653527,-73.9952614,-73.9803588,-73.9790728,-73.980691,-73.9843651,-73.9838136,-74.0019233,-74.0003969,-74.0018494,-74.000013,-74.0011691,-74.002141,-73.9814645,-73.98569,-73.9872728,-73.9880763,-73.984036,-73.9920697,-73.9838982,-73.9834047,-73.9834047,-73.9830259,-73.9882472,-73.9891893,-73.9788018,-73.9900119,-73.9819469,-73.9946144,-73.9867076,-73.9779409,-73.9912338,-73.9869946,-73.9781737,-73.9872281,-73.9883351,-73.9774423,-73.9880805,-73.9936489,-73.9867714,-73.9828704,-73.9883958,-73.9828704,-73.9945527,-73.9831636,-73.9839514,-73.9807805,-73.9793407,-74.005017,-74.0042175,-74.0030054,-74.0031343,-74.0036349,-74.003031,-74.0022306,-74.0033717,-74.0031865,-74.0014362,-74.0013473,-74.0005218,-74.0014372,-74.0016678,-74.000314,-74.0009892,-73.9790395,-73.9735986,-73.9905152,-73.9799726,-73.9910524,-73.9643508,-73.9644294,-73.9683607,-73.9672695,-73.9687578,-73.9993382,-73.999752,-73.995321,-73.9983778,-73.9876474,-74.0003231,-73.9999408,-73.9689802,-73.9695477,-73.9684855,-73.9700904,-73.9688452,-73.9718457,-73.9720294,-73.970671,-73.9720574,-73.9746695,-73.9874535,-73.9765061,-73.9767512,-73.9768992,-73.9767973,-73.9762776,-73.9772353,-73.9769653,-73.975869,-73.9983379,-73.9974449,-73.9930147,-73.9947843,-73.993399,-73.9865052,-73.9895336,-73.976455,-73.9828007,-73.9789431,-73.9806841,-73.9789915,-73.977338,-73.9782801,-73.9983379,-73.9989915,-73.9974193],null,null,null,{"interactive":true,"draggable":false,"keyboard":true,"title":"","alt":"","zIndexOffset":0,"opacity":1,"riseOnHover":false,"riseOffset":250},["Pugsley's Pizza","Williamsburg Pizza","99 Cent Fresh Pizza","Nino's 46","La Pizza Fresca Ristorante","La Gusto Pizza","Cheesy Pizza","Sal & Carmine's Pizza","MAMA'S TOO!","Bond 45","Casa D'amici","Pizza Al's","Colasante's Ristorante & Pub","Love & Dough","Patsy's Pizzeria","Louie & Ernie's Pizza","Pizza Barn","Mama's Pizza","Dulono's Pizza","Cheetah Pizza","Fat Lorenzo's","Red's Savoy Pizza","Frank From Philly & Andrea Pizza","Young Joni","Cossetta Alimentari","Pizza Luce","Football Pizza","Star Tavern","LA Traviata Pizzeria","Percy's Pizza","Pizza Land","Little Italy Pizza","Re Sette","B & W Deli & Pizzeria","Mediterraneo Restaurant","La Bellezza Pizza","Tre Sorelle","Rubby's Pizzeria","Justino's Pizzeria","Casabianca Pizzeria","Sottosuolo NYC","Mariella Pizza","Bella Blu","John & Tony's","Angelo's Pizzeria","Il Forno Pizza","Scarr's Pizza","Double Zero","Buca di Beppo Italian Restaurant","Rico's Pizza","Palermo's 95th","Giordano's","Gino's East - Magnificent Mile","Lou Malnati's Pizzeria","Georgio's Gourmet Pizza","Armand's Pizzeria","Pequod's Pizzeria","Geo's Pizza","Goodfellas Pizzeria","BazbeauxPizza","Napolese Pizzeria","The Wig & Pen Pizza Pub","Casey's General Store","Bearno's By the Bridge","The Original Impellizeri's Pizza","The Post","Churchill Downs","Cottage Inn Pizza - Ann Arbor","New York Pizza Depot","Pizza House","Backroom Pizza","Buddy's Pizza","Leone's Pizza","Adriatico's New York Style Pizza","Sicilia Fine Italian Specialties","The O Patio & Pub","Catfish Biff's Pizza & Subs","GoreMade Pizza","Pies & Pints - Lexington","Pazzo's Pizza Pub","PieTana","Belleria Pizzeria","Bruno Bros Pizza","Wedgewood Fernando's Pizza - Austintown","Avalon Downtown Pizzeria","Brier Hill Pizza & Wings","Fox's Pizza Den","Sparky's Pizzeria and Grill","Black Sheep Pizza - Minneapolis","Benny Marzano's","Imperial Pizza","Mellow Mushroom","Marcello's Pizza & Subs","Piu Bello Pizzeria Restaurant","Buckhead Pizza","Cosmo's Original Little Italy Pizza","Fellini's Pizza","Antico Pizza","Slice Downtown","Hawthorne's NY Pizza & Bar","Pizza Joint","Empire Slice House","Santucci's Original Square Pizza","Lorenzo & Sons Pizza","Santillo's Brick Oven Pizza","Kinchley's Tavern","Ralph's Pizzeria","Costco","Pizza Town USA","Brother's Pizzeria","Mama Rosa Pizza and Pasta","Denino's Pizzeria Tavern","The New Park Tavern","Vesta Wood Fired Pizza & Bar","Lee's Tavern","The Original Goodfella's Brick Oven Pizza","Tony Boloney's","Krispy Pizza","Mario's Classic Pizza","Johnny Pepperoni","Basile's Pizza","Benny Tudino's Pizzeria","Napoli's Brick Oven Pizza","Picasso Pizza","Pomodoro Pizza","SIMÒ PIZZA","Steve's Pizza","The Woodstock","The Grotto Pizzeria & Ristorante","Georgio Pizzeria","Pranzo Pizza & Pasta","Justino's Pizzeria","Adrienne's Pizzabar","Open Market","Da Vinci Pizza","Cucina Bene","Majestic Pizza","Underground Pizza","Neapolitan Express","Stage Door Pizza","Friendly Gourmet Pizza","Dona Bella Pizza","Harry's Italian","Adoro Lei","Girello","Little Italy Pizza","Lucali","Il Mattone West Village","5 Boroughs Pizza","Wild","Rossetti's Pizza","Serafina Meatpacking","Phil's Pizza","Saluggi's","Artichoke Basille's Pizza","Brunetti Pizza","Gaslight Pizzeria","Emily - West Village","Starbucks Reserve Roastery","Black Square Pizza","Bleecker Street Pizza","Enzo Bruni La Pizza Gourmet","Famous Ben's Pizza","John's of Bleecker Street","Filaga Pizzeria","Emmett's","Numero 28 Pizzeria - West Village","Kesté Pizza & Vino","Jekyll & Hyde","King's Pizza","Eddie & Sam's NY Pizza","Home Slice Pizza","Big Lou's Pizza","Pizzarita's","Julian's Italian Pizzeria & Kitchen","Chuck E. Cheese's","Napoli Pizza","Biggie's Pizza","Steve's Pizza","Lucali","Mister O1- South Beach","Pizza Girls WPB","Pizza Al Fresco","Totonno's","L & B Spumoni Gardens","Di Fara Pizza","Da Nonna Rosa","Ciro's Pizzeria & Beerhouse","Bronx Pizza","Filippi's Pizza Grotto Pacific Beach","Manhattan Pizzeria","Joe's Pizza","Vito's Pizza","Bonanno's New York Pizzeria","Bonanno's New York Pizzeria","Five50 Pizza Bar","Secret Pizza","Snacks","XS Nightclub","Encore Beach Club","Naked City Pizza Shop","Good Pie","Evel Pie","Pizza Rock","Acquolina","Pope's Italian Restaurant","Nove Italian Restaurant","Mama Mia's Restaurant","Marino's Pizza","Gennaro's Pizza Parlor","Pies on Wheels","Caputo's Pizzeria","Intrepid Summer Movie Series","42nd Street Pizza","Corner Slice","Francesca's Restaurant & Pizzeria","Café Crust","Borrelli's","King Umberto's of Elmont","New Park Pizza","Umberto's Pizzeria & Restaurant","Dani's House of Pizza","Rosa's Pizza","Brooklyn's Homeslice Pizzeria","Not Ray's Pizza","Roberta's","Little Vincent's Pizza","Carmine's Pizzeria","Sal's Pizzeria","Tony's Pizza","L'industrie Pizzeria","Best Pizza","Grimaldi's","Juliana's Pizza","Ignazio's","La Nonna Krispy Krust Pizza","Alphonso's Pizzeria & Trattoria","Paulie Gee's Slice Shop","Canal Pizza","Melani Pizzeria","Paulie Gee's","Speedy Romeo","Rizzo's Fine Pizza","Stanton Pizza","Solo Pizza","La Margarita Pizza","Luna Ristorante","Rosario's Pizza","F & M Slice Pizza","Da Gennaro","Margherita NYC","Yankee Pizza","Il Piccolo Bufalo","Da Nico Ristorante","Little Gio's Pizza","Lil' Frankie's","Sal's Little Italy","Ciao Vineria con Cucina","Gnocco","Pasquale Jones","Lombardi's Pizza","Champion Pizza","Pomodoro Ristorante & Pizzeria","Emporio","Prince Street Pizza","Rubirosa","Proto's Pizza","310 Bowery Bar","La Rossa","Stromboli Pizza","Baker's Pizza","East Village Pizza","Joe & Pat's Pizzeria","Muzzarella Pizza","Sorbillo Pizzeria","Joey's Pizzeria","Pizza Barbone","Palio Pizzeria","Oath Pizza - Nantucket","Steamboat Wharf Pizza","Fusaro's","Pi Pizzeria","Sophie T's Pizza","Muse Pizza","Moto Pizza","Poopsie's","Monte's Restaurant","Bianchi's Pizza","Giordano's Restaurant","Slice Of Edgartown","Isola","Santarpio's Pizza","Rocco's Pizzeria","Rinas Pizzeria & Cafe","Galleria Umberto","Pushcart Pizzeria","Regina Pizzeria","Ducali","1000 Degrees Neapolitan Pizzeria","Halftime Pizza","Florina Pizzeria & Paninoteca","Rosie's Subs and Pizza","Felcaro Pizzeria","Dirty Water Dough","Eataly Boston","Lynwood Cafe","Fenway Park","Baldie's Pizza & Subs","Cape Cod Cafe","Louie's Pizza","Town Spa Pizza","Frank Pepe Pizzeria Napoletana - Chestnut Hill","Tony's Place","Chilmark General Store","Bill's Pizzeria Kitchen + Grille","Regina Pizzeria","Modern Apizza","Frank Pepe Pizzeria Napoletana","Sally's Apizza","BAR","Riko's Pizza","Colony Grill","Johnny's Pizzeria","Full Moon Pizzeria","Nick's Pizza","Pie Pie Pizza","Mama's Pizzeria","PQR","Vinnie's Pizzeria","Va Bene","Salvo's Pizzabar","La Mia Pizza","Italian Village Pizzeria","Buchetta Brick Oven Pizza","Broadway Pizza & Restaurant","Saba's Pizza","Cafe Viva","Pizza Park","Pizza Pete's","Manhattan Brick Oven Pizza","Sutton Pizzeria","Oath Pizza - East 67th Street","Brooklyn Pizza Masters","Made In New York Pizza","Kiss My Slice","Farinella Bakery Pizza","Cafe Daniello's","Gato","Freddie & Pepper's","Big Nick's Burger & Pizza Joint Too","Francesco's Pizzeria","Iggy's Pizzeria","Motorino","Il Corallo Trattoria","Arturo's","Song E Napule","Fiore's Pizza","Denino's Greenwich Village","Joe's Pizza","Cafe Fiorello","Sfila Pizza","Sacco Pizza","Merilu Pizza Al Metro","Bricco Ristorante Italiano","New York Sal's Pizza","Mariella Pizza","Luigi's Pizza","Luigi's Gourmet Grill","Joe G Pizza & Restaurant","B Side Pizza & Wine Bar","Uncle Mario's Brick Oven Pizza","Bella Vita Pizzeria","IPizzaNY","Serafina Broadway","Claudio Pizzeria","Don Antonio","Angelo's Coal Oven Pizzeria","Nizza","Z Deli Pizzeria","Pazza Notte","Carve","A Slice of New York","PizzArte","Daniela Trattoria","Capizzi","Patzeria Perfect Pizza","Pasta Lovers","John's of Times Square","Radio City Pizza","Tavola","Vinny Vincenz","Sauce Pizzeria","Pisa Pizza","Frank's Trattoria","Pepe Giallo","Don Giovanni Ristorante","Ovest Pizzoteca by Luzzo's","10th Avenue Pizza & Cafe","Stella's Pizza","Gotham Pizza","Highline Pizza","Rocky's Pizza 14th St","Village Pizza","Pizza Italia","Famous Original Ray's Pizza","Company","Two Boots West Village","Rivoli Pizza","Pizza Rollio","Rosemary's Pizza","Teresa's Brick Oven Pizza & Cafe","Pizza Da Solo","Kiss My Slice","Harry's Italian Pizza Bar","Upside Pizza","Sofia Pizza Shoppe","Marinara Pizza","Cassiano's Pizza","Primavera Pizza & Pasta","Belmora Pizza & Restaurant","Zia Maria-Chelsea","Joe's Pizza","NY Pizza Suprema","3 Giovani","Rock Pizza Scissors","Ben's Pizzeria","Olio e Piú","D Napoli Pizza","My Pie Pizzeria Romana","Angelo Bellini","Pizza By Certé","La Vera Pizzeria & Restaurant","Aperitivo Pizza Bar","La Bellezza","La Trattoria","Patsy's Pizzeria","Picciotto NYC","Jiannetto's Pizza Truck","Deli On Madison","Naples 45 Ristorante E Pizzeria","Uncle Paul's Pizza","Previti Pizza","Royal Pizza","Prova Pizzabar","Giuseppe's Pizza","Garlic New York Pizza Bar","Lions & Tigers & Squares Detroit Pizza","Lombardi's pizza","Famous Famiglia Pizzeria","Famous Amadeus Pizza","Amtrak","Nicoletta Pizzeria","Lazzara's Pizza","Rocky's Number II","Posto","Patrizia's Pizza and Pasta","Mike's Pizza","Joey Pepperoni's Pizza","Libretto's Pizzeria","Brick Oven Pizza 33","Chelsea Pizza 23","J's Pizza","Rocco's Pizza Joint"],null,null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"setView":[[40.7451535,-73.993399],10,[]],"limits":{"lat":[25.7917344,45.0010473],"lng":[-122.4090769,-70.0858313]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
